### ISSUE TITLE
Verification for the plugin needed since firefox 45

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/JabFox#13]
The plugin could not be installed since verification was not performed.

Please ensure that the plugin firebib.xpi is verified by Mozilla.

Regards

Bernhard

**Comment by tobiasdiez** [comment]
Thanks for reporting this issue. I'm aware of these verification problems. 

The plan is finish/implement a few [issues](https://github.com/JabRef/JabFox/issues) and then put the addon on Firefox' central repository, see #8. This is the only way to solve the verification problems, but will take some time. Until then you can disable the verification as described in the answer to ["What are my options if I want to install unsigned extensions in Firefox? "](https://wiki.mozilla.org/Add-ons/Extension_Signing).

I close this issue since it is essentially a duplicate of #8.

**Comment by tobiasdiez** [comment]
The addon is now signed and can be installed directly via https://addons.mozilla.org/en-US/firefox/addon/jabfox/.

**Comment by ajbelle** [comment]
Works a treat (Win7-Firefox45.0.1), one click instal, then oneclick and it opens the record in JabRef. Pulls full bibliographic information that I can't even find a link to.  THX for getting it signed.
