### ISSUE TITLE
Indicate whether reference is alreay in JabRef

### ISSUE THREAD

**Issue by koppor** [JabRef/JabFox#32]
The JR icon should be green if the reference is already present in JabRef. If I click on the green icon, the reference is focused in JabRef.

**Comment by tobiasdiez** [comment]
In principle it is a nice idea. However:
- JabRef provides no interface to query if an entry is already in the db (right?)
- In order to get the BibEntry, the Zotero translator has to parse the website which is a noticeable overhead (since it always downloads associated pdfs).
- How do you handle multiple open databases? Which db should be taken if Jabref is not open?
- What happens if an almost-duplicate is in your database?

In view of these problems, I think that the current solution (JabFox does not know about your entries, but JabRef warns if you try to import a duplicate) is the best option we have at the moment.
