### ISSUE TITLE
Wiley publications cannot be imported anymore

### ISSUE THREAD

**Issue by AEgit** [JabRef/JabFox#45]
JabFox does not seem to work anymore for Wiley publications. When trying to import an item only a new entry with the title "Error" is generated. Example:
https://onlinelibrary.wiley.com/doi/full/10.1111/afe.12283

This is probably related to the fact, that an old Zotero version needs to be used to be able to run JabFox.

**Comment by tobiasdiez** [comment]
I can confirm the issue (even with the new version that includes updated zotero translators). The Browser Console reports
> Error: HTTP request to https://onlinelibrary.wiley.com/doi/full/10.1111/abstract rejected with status 404

and indeed if I follow the link I get a 404 error. Thus this seems to be problem with zotero. The discussion at https://forums.zotero.org/discussion/69819/wiley-online-library-import-problem suggests that you have to have access to the fulltext in order to successfully extract information from it.

I know this is a lot to ask, by can you to try out importing through zotero directly and see if its works for you or not.

**Comment by AEgit** [comment]
It does not work with the old Zotero version (needed for the previous JabFox version). It also gives an error with the new Zotero version, but the import still works (as Zotero provides different ways of importing articles, e.g. using "Atypon Journals").

**Comment by tobiasdiez** [comment]
Ok, in this case there is nothing I can do and would ask you to report the issue at https://github.com/zotero/translators/issues. Maybe as part of the related (?) issue https://github.com/zotero/translators/issues/1608.

**Comment by AEgit** [comment]
Done: https://github.com/zotero/translators/issues/1608#issuecomment-378174213

Thank you for pointing this out. Let's hope that the Zotero team will quickly fix things :D

**Comment by zuphilip** [comment]
Fixed with https://github.com/zotero/translators/pull/1624/files.

**Comment by AEgit** [comment]
Thank you - I guess this patch still needs to make it into the master build (?).

**Comment by AEgit** [comment]
Nevermind, Zotero has now been updated. See: https://github.com/zotero/translators/issues/1608#issuecomment-383400303

Thank you very much!
